name: Add Issue

on:
  issues:
    types:
      - assigned

jobs:
  add-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
      with: 
          project: capstone-project
          column: New Issues
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Add Issue
      run: |
        echo "Adding issue to repository..."
        cat ISSUE_TEMPLATE.md >> $GITHUB_EVENT_PATH
